parameters:
    restore: true

steps:
- task: DotNetCoreInstaller@2
  displayName: Install .Net Core SDK
  inputs:
    packageType: sdk
    version: 2.2.402

- script: dotnet --info
  displayName: Show dotnet SDK info

- task: NuGetToolInstaller@0
  displayName: Pin nuget version
  inputs:
    versionSpec: 5.2.0

- ${{ if eq(parameters.restore, 'true') }}:
  - powershell: dotnet restore src\Pty.Net.sln
    displayName: Restore NuGet packages

- script: |
    dotnet tool install --tool-path . nbgv
  displayName: Install gitversioning tool

- task: PowerShell@2
  inputs:
    filePath: azure-pipelines/variables/_pipelines.ps1
    failOnStderr: true
  displayName: Set pipeline variables based on source

