steps:
- task: DotNetCoreInstaller@2
  displayName: Install .Net Core SDK
  inputs:
    packageType: sdk
    version: 2.2.402

- script: dotnet --info
  displayName: Show dotnet SDK info

- task: NuGetToolInstaller@0
  displayName: Pin nuget version
  inputs:
    versionSpec: 5.2.0

- powershell: dotnet restore src\Pty.Net.sln
  displayName: Restore NuGet packages

- script: |
    dotnet tool install --tool-path . nbgv
  displayName: Install gitversioning tool

